### ISSUE TITLE
Named spacing units

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/ui#16]
**Named spacing units**
Similarly to the [Shopify design library](https://polaris.shopify.com/components), it'd be helpful to have named spacing units, for the most frequently occurring values.

```jsx
//
// An example of names, could also go 
// for tight/loose or some other system
<Text textStyle="display" pb={['small', 'medium', 'large']}>
```

The benefit of this is having more natural language with which to align on and discuss layouts. Units become more relatable. `small` is clearly small, whereas the size of an `8` is either big or small depending on the scaling units used. 
Consistency is enforced by encouraging use of these units. Number-based units only being used in the case of exceptions. Helpful errors keep things tidy, such as in the case where a number that has a corresponding alias is used.

Thoughts?

**Comment by markmhx** [comment]
Assigning to @jasperjansz so he can produce another design iteration here.

**Comment by jasperjansz** [comment]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/3501a5e0-db6c-45ee-ac54-9af6b6eac0ba)

We can copy these exactly. These are the values I use most in the design. However, keep in mind there will be cases where the spacing will be larger than these values, e.g. 64px. It's not common but it will happen.

@aulneau @kyranjamie
