### ISSUE TITLE
Align buttons with style guide

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/ui#28]
- [ ] Adjust heights/font-weights.
- [ ] Remove unused sizes
- [ ] [Change the colour of the blue disabled button](https://github.com/blockstack/blockstack-app/issues/88)

**Comment by timstackblock** [comment]
The secret Key font, height and alignment looks good. 

I think the different shade of blue looks good, but I am slightly color blind so I will get s second opinion.

![Screen Shot 2020-02-19 at 8.45.09 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/2fff0b71-f17e-4945-9c6f-7081b0484ee8)
